services:
  bmw_telemetry:
    build: .
    # volumes:
    #   - .:/ros2_ws
    stdin_open: true # Equivalent to -i
    tty: true # Equivalent to -t
    environment:
      - DISPLAY=host.docker.internal:0.0
    command: bash -c "source /opt/ros/humble/setup.sh && colcon build && source install/setup.bash && bash"
